# Generated by Django 4.2.3 on 2023-07-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Baby Care'), (2, 'Women Care'), (3, 'Covid Essentials'), (4, 'Personal care')], verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
